// Node Plugin Service Protocol Buffer Definition
// Version: 2.0.0
//
// 这个文件定义了节点插件的 gRPC 服务接口
// 设计原则：
// 1. 类型安全：使用结构化消息替代 JSON 字符串
// 2. 可扩展：预留字段号，使用 oneof 支持多种响应类型
// 3. 可追踪：包含执行上下文和追踪信息
// 4. 向后兼容：遵循 protobuf 最佳实践

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/node_plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodePluginService_GetMetadata_FullMethodName      = "/node_plugin.NodePluginService/GetMetadata"
	NodePluginService_Init_FullMethodName             = "/node_plugin.NodePluginService/Init"
	NodePluginService_Run_FullMethodName              = "/node_plugin.NodePluginService/Run"
	NodePluginService_SubscribeTrigger_FullMethodName = "/node_plugin.NodePluginService/SubscribeTrigger"
	NodePluginService_Stop_FullMethodName             = "/node_plugin.NodePluginService/Stop"
	NodePluginService_TestCredential_FullMethodName   = "/node_plugin.NodePluginService/TestCredential"
	NodePluginService_HealthCheck_FullMethodName      = "/node_plugin.NodePluginService/HealthCheck"
)

// NodePluginServiceClient is the client API for NodePluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodePluginService 定义节点插件的 gRPC 服务接口
type NodePluginServiceClient interface {
	// GetMetadata 获取插件元数据（插件能力描述）
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	// Init 初始化节点（在执行前调用）
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// Run 执行节点（支持流式输出）
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error)
	// SubscribeTrigger 触发事件订阅（服务端作为客户端读取插件推送的事件）
	// 仅当插件分类为 CATEGORY_TRIGGER 时由服务端主动调用，插件通过流式响应推送事件
	SubscribeTrigger(ctx context.Context, in *SubscribeTriggerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TriggerEvent], error)
	// Stop 停止正在执行的节点（优雅停止）
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// TestCredential 测试凭证有效性
	TestCredential(ctx context.Context, in *TestCredentialRequest, opts ...grpc.CallOption) (*TestCredentialResponse, error)
	// HealthCheck 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nodePluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodePluginServiceClient(cc grpc.ClientConnInterface) NodePluginServiceClient {
	return &nodePluginServiceClient{cc}
}

func (c *nodePluginServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, NodePluginService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, NodePluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodePluginService_ServiceDesc.Streams[0], NodePluginService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodePluginService_RunClient = grpc.ServerStreamingClient[RunResponse]

func (c *nodePluginServiceClient) SubscribeTrigger(ctx context.Context, in *SubscribeTriggerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TriggerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodePluginService_ServiceDesc.Streams[1], NodePluginService_SubscribeTrigger_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTriggerRequest, TriggerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodePluginService_SubscribeTriggerClient = grpc.ServerStreamingClient[TriggerEvent]

func (c *nodePluginServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, NodePluginService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginServiceClient) TestCredential(ctx context.Context, in *TestCredentialRequest, opts ...grpc.CallOption) (*TestCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestCredentialResponse)
	err := c.cc.Invoke(ctx, NodePluginService_TestCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodePluginServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NodePluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodePluginServiceServer is the server API for NodePluginService service.
// All implementations must embed UnimplementedNodePluginServiceServer
// for forward compatibility.
//
// NodePluginService 定义节点插件的 gRPC 服务接口
type NodePluginServiceServer interface {
	// GetMetadata 获取插件元数据（插件能力描述）
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	// Init 初始化节点（在执行前调用）
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// Run 执行节点（支持流式输出）
	Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error
	// SubscribeTrigger 触发事件订阅（服务端作为客户端读取插件推送的事件）
	// 仅当插件分类为 CATEGORY_TRIGGER 时由服务端主动调用，插件通过流式响应推送事件
	SubscribeTrigger(*SubscribeTriggerRequest, grpc.ServerStreamingServer[TriggerEvent]) error
	// Stop 停止正在执行的节点（优雅停止）
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// TestCredential 测试凭证有效性
	TestCredential(context.Context, *TestCredentialRequest) (*TestCredentialResponse, error)
	// HealthCheck 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNodePluginServiceServer()
}

// UnimplementedNodePluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodePluginServiceServer struct{}

func (UnimplementedNodePluginServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedNodePluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedNodePluginServiceServer) Run(*RunRequest, grpc.ServerStreamingServer[RunResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedNodePluginServiceServer) SubscribeTrigger(*SubscribeTriggerRequest, grpc.ServerStreamingServer[TriggerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTrigger not implemented")
}
func (UnimplementedNodePluginServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedNodePluginServiceServer) TestCredential(context.Context, *TestCredentialRequest) (*TestCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestCredential not implemented")
}
func (UnimplementedNodePluginServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNodePluginServiceServer) mustEmbedUnimplementedNodePluginServiceServer() {}
func (UnimplementedNodePluginServiceServer) testEmbeddedByValue()                           {}

// UnsafeNodePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodePluginServiceServer will
// result in compilation errors.
type UnsafeNodePluginServiceServer interface {
	mustEmbedUnimplementedNodePluginServiceServer()
}

func RegisterNodePluginServiceServer(s grpc.ServiceRegistrar, srv NodePluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodePluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodePluginService_ServiceDesc, srv)
}

func _NodePluginService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePluginService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePluginService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodePluginServiceServer).Run(m, &grpc.GenericServerStream[RunRequest, RunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodePluginService_RunServer = grpc.ServerStreamingServer[RunResponse]

func _NodePluginService_SubscribeTrigger_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTriggerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodePluginServiceServer).SubscribeTrigger(m, &grpc.GenericServerStream[SubscribeTriggerRequest, TriggerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodePluginService_SubscribeTriggerServer = grpc.ServerStreamingServer[TriggerEvent]

func _NodePluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePluginService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePluginService_TestCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServiceServer).TestCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePluginService_TestCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServiceServer).TestCredential(ctx, req.(*TestCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodePluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodePluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodePluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodePluginServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodePluginService_ServiceDesc is the grpc.ServiceDesc for NodePluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodePluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node_plugin.NodePluginService",
	HandlerType: (*NodePluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _NodePluginService_GetMetadata_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _NodePluginService_Init_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _NodePluginService_Stop_Handler,
		},
		{
			MethodName: "TestCredential",
			Handler:    _NodePluginService_TestCredential_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NodePluginService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _NodePluginService_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTrigger",
			Handler:       _NodePluginService_SubscribeTrigger_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/node_plugin.proto",
}
