# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import node_plugin_pb2 as node__plugin__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in node_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodePluginServiceStub(object):
    """注意：为简化跨语言兼容性，使用 int64 毫秒时间戳替代 google.protobuf.Timestamp

    =============================================================================
    服务定义
    =============================================================================

    NodePluginService 定义节点插件的 gRPC 服务接口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
                '/node_plugin.NodePluginService/GetMetadata',
                request_serializer=node__plugin__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.GetMetadataResponse.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/node_plugin.NodePluginService/Init',
                request_serializer=node__plugin__pb2.InitRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Run = channel.unary_stream(
                '/node_plugin.NodePluginService/Run',
                request_serializer=node__plugin__pb2.RunRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.RunResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/node_plugin.NodePluginService/Stop',
                request_serializer=node__plugin__pb2.StopRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.StopResponse.FromString,
                _registered_method=True)
        self.TestCredential = channel.unary_unary(
                '/node_plugin.NodePluginService/TestCredential',
                request_serializer=node__plugin__pb2.TestCredentialRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.TestCredentialResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/node_plugin.NodePluginService/HealthCheck',
                request_serializer=node__plugin__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=node__plugin__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class NodePluginServiceServicer(object):
    """注意：为简化跨语言兼容性，使用 int64 毫秒时间戳替代 google.protobuf.Timestamp

    =============================================================================
    服务定义
    =============================================================================

    NodePluginService 定义节点插件的 gRPC 服务接口
    """

    def GetMetadata(self, request, context):
        """GetMetadata 获取插件元数据（插件能力描述）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Init 初始化节点（在执行前调用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Run 执行节点（支持流式输出）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop 停止正在执行的节点（优雅停止）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestCredential(self, request, context):
        """TestCredential 测试凭证有效性
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck 健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodePluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=node__plugin__pb2.GetMetadataRequest.FromString,
                    response_serializer=node__plugin__pb2.GetMetadataResponse.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=node__plugin__pb2.InitRequest.FromString,
                    response_serializer=node__plugin__pb2.InitResponse.SerializeToString,
            ),
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=node__plugin__pb2.RunRequest.FromString,
                    response_serializer=node__plugin__pb2.RunResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=node__plugin__pb2.StopRequest.FromString,
                    response_serializer=node__plugin__pb2.StopResponse.SerializeToString,
            ),
            'TestCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.TestCredential,
                    request_deserializer=node__plugin__pb2.TestCredentialRequest.FromString,
                    response_serializer=node__plugin__pb2.TestCredentialResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=node__plugin__pb2.HealthCheckRequest.FromString,
                    response_serializer=node__plugin__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'node_plugin.NodePluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('node_plugin.NodePluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodePluginService(object):
    """注意：为简化跨语言兼容性，使用 int64 毫秒时间戳替代 google.protobuf.Timestamp

    =============================================================================
    服务定义
    =============================================================================

    NodePluginService 定义节点插件的 gRPC 服务接口
    """

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_plugin.NodePluginService/GetMetadata',
            node__plugin__pb2.GetMetadataRequest.SerializeToString,
            node__plugin__pb2.GetMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_plugin.NodePluginService/Init',
            node__plugin__pb2.InitRequest.SerializeToString,
            node__plugin__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/node_plugin.NodePluginService/Run',
            node__plugin__pb2.RunRequest.SerializeToString,
            node__plugin__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_plugin.NodePluginService/Stop',
            node__plugin__pb2.StopRequest.SerializeToString,
            node__plugin__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_plugin.NodePluginService/TestCredential',
            node__plugin__pb2.TestCredentialRequest.SerializeToString,
            node__plugin__pb2.TestCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/node_plugin.NodePluginService/HealthCheck',
            node__plugin__pb2.HealthCheckRequest.SerializeToString,
            node__plugin__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
